abstract: SASL Authentication framework
author: Graham Barr <gbarr@pobox.com>
distribution_type: module
generated_by: Module::Install version 0.61
license: perl
name: Authen-SASL
no_index: 
  directory: 
    - inc
    - t
requires: 
  perl: 5.005
version: 2.10
