name: Authen-SASL
version: 2.09
abstract: SASL Authentication framework
author: Graham Barr <gbarr@pobox.com>
license: perl
distribution_type: module
requires:
  perl: 5.005
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
