name: Authen-SASL
version: 2.07
abstract: SASL Authentication framework
author: Graham Barr <gbarr@pobox.com>
license: perl
distribution_type: module
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.31
